// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://trefqvcqakxzikosdelp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRyZWZxdmNxYWt4emlrb3NkZWxwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5NDQ3MTUsImV4cCI6MjA1NjUyMDcxNX0.KJ4foV_qvi2V4h_GhSHNPkP52vHvnpEYtIOSdmN9k3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);